# Generated by Django 5.2.7 on 2025-10-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='degree_type',
            field=models.CharField(choices=[('licence_fondamentale', 'Licence Fondamentale'), ('licence_pro', 'Licence Professionnelle'), ('bachelor', 'Bachelor'), ('master_recherche', 'Master de Recherche'), ('master_pro', 'Master Professionnel'), ('phd', 'PhD / Doctorate'), ('bts', 'BTS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('abandoned', 'Abandoned'), ('graduated', 'Graduated')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('maitre_assistant', 'Maître Assistant'), ('maitre_de_conferences', 'Maître de Conférences'), ('professeur', 'Professeur Titulaire'), ('docteur', 'Docteur'), ('autre', 'Autre')], default='docteur', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('vacataire', 'Vacataire'), ('contractuel', 'Contractuel')], default='permanent', max_length=50),
        ),
    ]
