# Generated by Django 5.2.7 on 2025-10-29 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/')),
                ('file_type', models.CharField(choices=[('students', 'Students'), ('programs', 'Programs'), ('courses', 'Courses'), ('enrollments', 'Enrollments'), ('results', 'Results')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('error', 'Error')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data_loader.importfile')),
            ],
        ),
    ]
